// This file is auto-generated by @tanstack/router-cli
// Run: npx @tanstack/router-cli@latest tsr

import { RootRoute } from "@tanstack/react-router";
import { Route as IndexRoute } from "./routes/index";
import { Route as RootRoute } from "./routes/__root";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof RootRoute;
    };
  }
}

export const routeTree = RootRoute.addChildren([IndexRoute]);
